### ISSUE TITLE
New GCC complains about misleading indentation in port.c#L86-L87

### ISSUE THREAD

**Issue by drawkula** [dbetz/p1load#5]
https://github.com/dbetz/p1load/blob/master/port.c#L86-L87
```
    if (info->verbose)
        printf("Trying %s                    \n", port); fflush(stdout);
```
Newer GCCs (e.g. 6.3.0) complain about misleading indentation here.

**Comment by dbetz** [comment]
That was not only misleading. It was wrong. I've pushed a fix. Thanks for pointing that out!
